// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqxoybukperipawyrdml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxeG95YnVrcGVyaXBhd3lyZG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0NjM4OTAsImV4cCI6MjA1MjAzOTg5MH0.uIJ-Eo_bzxICbTxgaCr5sjp9o5ewNe3795IKGQ5Sxv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);